# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nathanel Anandas
#title: Senior Network System Administrator
email: brett.h@email.co.uk
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I have 30 plus years of exhaustive experience in General Administration.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GOSHAR VENTURES PVT LTD
        link: https://goo.gl/maps/zFguQtRsJeYbyvhz8
        link_text: ONE BKC, B wing 701, BKC Bandra East, Mumbai - 400051
        sub_title: Outsource Manager
        caption: August 2017 - May 2020
        quote: >
          Job profile
        description: | # this will include new lines to allow paragraphs
            Coordinating with Proprietor and Partners of the company for
            BMC H.O., Estate Department, D.M.C, and Legal Department.
            Independently doing work with Office of District Collector
            (P.R.C. namechanging,Town Planning remarks, survey of land,
            subdivision, amalgamations)
            All B.M.C Wards office work including Licences-Shops,
            Factories, Permissions- Hoardings, neon sign different types
            display etc. HEW, Water-department, Assessment department
            Roads, (Parking lots)
            Co-Op. HSG. Registration and Charity commissioner off.
            work
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ARIISTO GROUP
        link: https://goo.gl/maps/pfh1TcuBbHia1XDW6
        link_text: N.S. Phadke Road, Near East West flyover Andheri (e) Mumbai-4000069
        sub_title: Liasoning Executive
        caption: April 2011 - August 2017
        quote: >
          Job profile
        description: | # this will include new lines to allow paragraphs
            Coordinating with Directors of the company for S.R.A.,BMC
            H.O. Mantralaye, MMRDA
            Independently doing City Survey Office work (P.R.C.name
            changing, C.T.S. plans,survey of land, subdivision,amalgamations)
            All sub-Registrar off’s work including old customs & IGR pune.
            Talati & Tahasildhar off’s all work (all over Maharashtra)
            BMC Off”s All Wards Licences-Shops, Factories, Permissions-
            Hoardings, neon sign different types display etc.
            HEW, Water-department, Roads,(Parking lots) Colony off. work
            Co-Op. HSG. Registration, Charity commissioner off. work
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          title: Sheetal Group of Companies
          link: https://goo.gl/maps/7LTUTXQvdZ2j5GhN8
          link_text: Sheetal Estates, Grant Road Mumbai-07
          sub_title: Project Coordinator
          caption: February 2005 - March 2011
          quote: >
            Job profile
          description:  | # this will include new lines to allow paragraphs
              Coordinating with different Directors/Partners of the
              Company.Coordinating with Solicitors/Lawyers/Advocates 
              for legal matters of company Coordinating with Consultants
              & Architects. Coordinating with Site In charge/Supervisor & Tenants. 

              Liasoning:

              Liasoning with government officials like BMC, MHADA, MMRDA, SRA , COLLECTOR and other local
              government officials for statutory compliance, liaison with legal authorities fro compliance and information.
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
        title: Parasrampuria Group
        link: https://goo.gl/maps/BQ6K6nuVoMZo3J3N7
        link_text: 10TH Floor Regent Chamber Nariman Point Mumbai-21
        sub_title: Administration Officer
        caption: September 1991 - February 2005
        quote: >
          Job profile
        description: | # this will include new lines to allow paragraphs
          Office management Recruitment of Class IV cadre viz:
          Drivers, Cleaners, Mechanics, Sweepers, Peons after assessing the
          Requirement. Assigning duties of Class IV employees.
          Ensure Maintenance of cleanliness and hygiene in and around the
          office premises at all times. Manage stationery requirements,
          negotiate with vendors for Stationery, approve purchase orders,
          bills and other payments for stationery, and ensure timely
          availability and distribution of stationery to staff.

          Liasoning:

          Liasoning with government officials like MSEB (Electricity) MTNL (telephone lines, leased lines, hotlines),
          MIDC (Industrial development issues) other local government officials for statutory compliance, liaison with
          legal authorities fro compliance and information exchange.

          Fleet management:

          Maintain a database of vehicles of the company.
          Ensure that files with relevant documents along with respective driving licenses are on record. Keep abreast of
          laws, regulations pertaining to vehicles viz, registration services, insurance, maintenance, etc.
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
        title: Bush India Limited
        link: https://goo.gl/maps/eBkBSPN9iRVYw6Wc7
        link_text: 3rd floor Zenith tin works opp. Race Course gate no.6 Mahalaxami Mumbai -24
        sub_title: Office Assistant
        caption: June 1991 - September 1991
        quote: >
          Job profile
        description: | # this will include new lines to allow paragraphs
          Filing Job, Record keeping of all branches on all India
          Basis, providing records to Auditors and Accountants, etc
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
        title: Usmania Bros
        link: https://goo.gl/maps/3bzVRjqtEA9fKd66A
        link_text: 154 Quay street 4th lane corner Darukhana Reay Road Mumbai -10
        sub_title: General Assistant
        caption: June 1985 - June 1990
        quote: >
          Job profile
        description: | # this will include new lines to allow paragraphs
          Making delivery challans, looking after loading and
          Unloading banking, payment collections etc.

  - title: Qualification # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mumbai University
        #caption: 2010 - 2013
        sub_title: B.Com
        quote: >
          The University of Mumbai (known earlier as University of Bombay) is one of the oldest and premier Universities in India est. in 1857.
        #description: | # this will include new lines to allow paragraphs
        #  During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Professional Qualification # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        #title: Mumbai University
        #caption: 2010 - 2013
        #sub_title: B.Com
        #quote: >
        #  The University of Mumbai (known earlier as University of Bombay) is one of the oldest and premier Universities in India est. in 1857.
        description: | # this will include new lines to allow paragraphs
          Passed Drawing Examination of Govt.of Maharashtra

          Elementary

          Intermediate
          
          NCC
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my Qualification and Work Experience I am also proficient in
      - Languages : English, Hindi, Marathi, Kannada, Telugu, Gujarati,
                    Tamil, Malayalam, Bhojpuri & Tulu.

      And i also enjoy
      - Painting
      - Singing

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
